### PR TITLE
/coinflip

### PR DESCRIPTION
**Pull request by lichmeh**
Added coinflip command
  Supports args of heads or tails to "call it in the air"
  Notifies if called correctly or not
  If not called, outputs results with a message to call it next time

### CODE REVIEW

**Comment by lichmeh** [comment]
Added coinflip command
  Supports args of heads or tails to "call it in the air"
  Notifies if called correctly or not
  If not called, outputs results with a message to call it next time

**Comment by freshlogic** [comment]
@lichmeh I'm not so sure the `Next time, try calling it in the air.` feature is obvious enough to understand that next time the user should try `/coinflip heads` or `/coinflip tails`. Any ideas on how to make that more understandable?

**Comment by lichmeh** [comment]
@freshlogic Maybe just by updating the message to state something like "Next time, try calling it in the air with /coinflip heads|tails" since there are only two options

**Comment by freshlogic** [comment]
@lichmeh I removed the "Next time, try calling it in the air" feature. I think we'd find that discoverability feature annoying showing up every time someone wants to do a simple `/coinflip`.

**Comment by lichmeh** [comment]
@freshlogic Makes sense.  I wanted a way for people to know it was there, but if it's posted as an option in the readme/forum with the commands, it won't be missed.

**Comment by lichmeh** [comment]
@freshlogic The "Next time" section still needs to be removed from the test files

**Comment by freshlogic** [comment]
Published v2.22.0 to NPM: https://www.npmjs.com/package/mehdown. Next step is to get this integrated to meh.com.

**Pull request merged**
